# Generated by Django 6.1 on 2026-09-10 13:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_comment_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicroPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=280)),
                ('type', models.CharField(choices=[('standard', 'Standard'), ('repost', 'Repost')], default='standard', max_length=10)),
                ('media', models.JSONField(blank=True, default=list)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('none', 'None')], default='none', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reposts', to='blog.micropost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='micro_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MicroPostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('micropost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blog.micropost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='micropost_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('micropost', 'user'), name='unique_micropost_user_like')],
            },
        ),
    ]
