# Generated by Django 5.0.14 on 2026-09-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='micropost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='microposts/'),
        ),
    ]
